-- Applied to Supabase production on 2026-09-21.
-- Adds immutable-style audit capture for core business tables.
-- See deployment notes; trigger uses auth.uid() and tenant company_id.
create table if not exists public.audit_logs (
 id bigint generated by default as identity primary key,
 company_id uuid not null references public.companies(id) on delete cascade,
 user_id uuid, action text not null check (action in ('INSERT','UPDATE','DELETE')),
 table_name text not null, record_id text, old_data jsonb, new_data jsonb,
 created_at timestamptz not null default now()
);
create index if not exists audit_logs_company_created_idx on public.audit_logs(company_id, created_at desc);
alter table public.audit_logs enable row level security;
